apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: bank-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.3.5
          ports:
            - containerPort: 9898
          livenessProbe:
            httpGet:
              path: /livez
              port: 9898
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9898
            initialDelaySeconds: 2
            periodSeconds: 5
